# Generated by Django 6.0.5 on 2026-05-31 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Firebase UID')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilcliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Cliente',
                'verbose_name_plural': 'Perfis dos Clientes',
            },
        ),
    ]
