# Generated by Django 6.0.5 on 2026-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(default='LJ Utilitários', max_length=100, verbose_name='Nome da Loja')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Apenas números com DDD, ex: 11999999999', max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_mensagem_template', models.TextField(default='🛒 *Novo Pedido #{{numero}}*\n\n👤 Cliente: {{nome}}\n📍 Cidade: {{cidade}}\n📞 Telefone: {{telefone}}\n🏠 Endereço: {{endereco}}\n\n*Itens:*\n{{lista_itens}}\n\n💰 Subtotal: R$ {{subtotal}}\n🚚 Frete: R$ {{frete}}\n💵 *Total: R$ {{total}}*\n\n📝 Obs: {{observacoes}}', verbose_name='Template da Mensagem')),
                ('cidade_base', models.CharField(blank=True, max_length=100, verbose_name='Cidade Base')),
                ('cidades_atendidas', models.TextField(blank=True, help_text='Separadas por vírgula', verbose_name='Cidades Atendidas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='loja/', verbose_name='Logo')),
                ('banner_principal', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Principal')),
                ('texto_banner', models.CharField(blank=True, default='Utilitários de Qualidade', max_length=200, verbose_name='Título do Banner')),
                ('subtexto_banner', models.CharField(blank=True, default='Entrega rápida na sua cidade', max_length=300, verbose_name='Subtexto do Banner')),
                ('frete_fixo', models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='Frete Fixo (R$)')),
                ('frete_gratis_acima', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Frete Grátis Acima de (R$)')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
