# Generated by Django 6.0.5 on 2026-05-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='frete_areal',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=8, verbose_name='Frete Areal'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='frete_bemposta',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Frete Bemposta'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='frete_levy',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8, verbose_name='Frete Com. Levy Gasparian'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='frete_paraiba_sul',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=8, verbose_name='Frete Paraíba do Sul'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='frete_tres_rios',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Cidade da loja — frete mais barato', max_digits=8, verbose_name='Frete Três Rios, RJ'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], default='aleatoria', max_length=20, verbose_name='Tipo da Chave Pix'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='whatsapp_mensagem_template',
            field=models.TextField(default='🛒 *Novo Pedido #{{numero}}* — L&J Utilitários\n\n👤 Cliente: {{nome}}\n📞 Telefone: {{telefone}}\n\n🚚 *Forma de Recebimento:* {{forma_recebimento}}\n{{info_entrega}}💳 *Forma de Pagamento:* {{forma_pagamento}}\n{{info_troco}}\n*Itens do Pedido:*\n{{lista_itens}}\n\n💰 Subtotal: R$ {{subtotal}}\n🚚 Frete: R$ {{frete}}\n💵 *TOTAL: R$ {{total}}*\n\n📝 Obs: {{observacoes}}\n🕐 {{data_hora}}', verbose_name='Template da Mensagem'),
        ),
    ]
