# Generated by Django 6.0.5 on 2026-06-01 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao_chave_pix_configuracao_frete_areal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='whatsapp_mensagem_template',
            field=models.TextField(default='🛒 *Novo Pedido #{{numero}}* — L&J Utilitários\n\n👤 *Cliente:* {{nome}}\n📞 *Telefone:* {{telefone}}\n\n🚚 *Forma de Recebimento:* {{forma_recebimento}}\n{{info_entrega}}\n\n💳 *Forma de Pagamento:* {{forma_pagamento}}\n{{info_troco}}\n\n🛍️ *Itens do Pedido:*\n{{lista_itens}}\n\n💰 Subtotal: R$ {{subtotal}}\n🚚 Frete: R$ {{frete}}\n💵 *TOTAL: R$ {{total}}*\n\n📝 *Obs:* {{observacoes}}\n🕐 Pedido em: {{data_hora}}', verbose_name='Template da Mensagem'),
        ),
        migrations.CreateModel(
            name='LogConsentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('acao', models.CharField(choices=[('aceite_cookies', 'Aceite de Cookies'), ('consentimento_checkout', 'Consentimento no Checkout'), ('aceite_termos_google', 'Aceite de Termos (Google Login)'), ('exclusao_conta', 'Exclusão de Conta')], max_length=50, verbose_name='Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_consentimento', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Consentimento',
                'verbose_name_plural': 'Logs de Consentimento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
