# Generated by Django 6.0.5 on 2026-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracao_whatsapp_mensagem_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='logo_navbar',
            field=models.ImageField(blank=True, help_text='Versão horizontal para a navbar. PNG transparente. Ideal: 240×80px', null=True, upload_to='loja/', verbose_name='Logo Navbar'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da loja. PNG com fundo transparente. Ideal: 200×200px', null=True, upload_to='loja/', verbose_name='Logo Principal'),
        ),
    ]
