# Generated by Django 6.0.5 on 2026-05-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix')], default='credito', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_recebimento',
            field=models.CharField(choices=[('entrega', 'Entrega no endereço'), ('retirada', 'Retirada na loja')], default='entrega', max_length=20, verbose_name='Forma de Recebimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco_para',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Troco para (R$)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_cliente',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
    ]
