# Generated by Django 6.0.5 on 2026-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_forma_pagamento_pedido_forma_recebimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, verbose_name='Consentimento LGPD'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_consentimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Consentimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ip_cliente',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Cliente'),
        ),
    ]
