# Generated by Django 6.0.5 on 2026-06-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone_emoji',
            field=models.CharField(blank=True, default='📦', help_text='Usado como fallback se não houver imagem.', max_length=10, verbose_name='Ícone (Emoji)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone_img',
            field=models.ImageField(blank=True, help_text='PNG recomendado. Tamanho ideal: 120×120px, fundo transparente.', null=True, upload_to='categorias/', verbose_name='Ícone (Imagem)'),
        ),
    ]
